name = "serviceeast"
main = "dashboard-worker-sla-sort.js"
compatibility_date = "2026-05-10"

workers_dev = true

kv_namespaces = [
  { binding = "CASTLE_KV", id = "40a59fd4804940d9acef76d64ee5405f" }
]

[triggers]
# Cron ปลุกทุก 1 นาที แต่ dashboard-worker.js จะตรวจจริงตามรอบที่ตั้งไว้ในหน้าเว็บ
crons = ["* * * * *"]
